services:
  event_dispatcher:
    class: Symfony\Component\EventDispatcher\EventDispatcher

  loader:
    class: Gammabeam82\Bot\Message\MessagePartsLoader
    arguments: ['%parts%']

  message_provider:
    class: Gammabeam82\Bot\Message\MessageProvider
    factory: [Gammabeam82\Bot\Factory\MessageProviderFactory, create]
    arguments: ['@loader']

  logger:
    class: Monolog\Logger
    factory: [Gammabeam82\Bot\Factory\LoggerFactory, create]

  botman_telegram:
    class: BotMan\BotMan\BotMan
    factory: [Gammabeam82\Bot\Factory\BotmanTelegramFactory, create]
    arguments: ['%telegram_token%']

  bot:
    public: true
    class: Gammabeam82\Bot\Bot
    arguments: ['@botman_telegram', '@message_provider', '@event_dispatcher']

  message_subscriber:
    class: Gammabeam82\Bot\EventListener\MessageSubscriber
    arguments: ['@logger']
    tags:
      - { name: kernel.event_subscriber }
